version: "2"
services:
  app_1:
    build: ./app
    links:
      - db
    ports:
      - "5001:5000"
    container_name: shop-app-1
  app_2:
    build: ./app
    links:
      - db
    ports:
      - "5002:5000"
    container_name: shop-app-2
  app_3:
    build: ./app
    links:
      - db
    ports:
      - "5003:5000"
    container_name: shop-app-3

  db:
    image: mysql:8.0.28
    ports:
      - "30000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database:/docker-entrypoint-initdb.d/:ro
    container_name: mysql-8_0
